// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AAlert: typeof import('ant-design-vue/es')['Alert']
    About: typeof import('./src/components/About.vue')['default']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AEmpty: typeof import('ant-design-vue/es')['Empty']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    AList: typeof import('ant-design-vue/es')['List']
    AListItem: typeof import('ant-design-vue/es')['ListItem']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuDivider: typeof import('ant-design-vue/es')['MenuDivider']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AMenuItemGroup: typeof import('ant-design-vue/es')['MenuItemGroup']
    APopover: typeof import('ant-design-vue/es')['Popover']
    AResult: typeof import('ant-design-vue/es')['Result']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    ATag: typeof import('ant-design-vue/es')['Tag']
    ATypographyText: typeof import('ant-design-vue/es')['TypographyText']
    ATypographyTitle: typeof import('ant-design-vue/es')['TypographyTitle']
    AuthenticationLogin: typeof import('./src/components/AuthenticationLogin.vue')['default']
    AuthenticationLogout: typeof import('./src/components/AuthenticationLogout.vue')['default']
    BaseLink: typeof import('./src/components/BaseLink.vue')['default']
    BasePage: typeof import('./src/components/BasePage.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    Layout: typeof import('./src/components/Layout.vue')['default']
    LayoutHeader: typeof import('./src/components/LayoutHeader.vue')['default']
    NotFound: typeof import('./src/components/NotFound.vue')['default']
    ProfileSetting: typeof import('./src/components/ProfileSetting.vue')['default']
    SobCreation: typeof import('./src/components/SobCreation.vue')['default']
    SobDetail: typeof import('./src/components/SobDetail.vue')['default']
    SobMain: typeof import('./src/components/SobMain.vue')['default']
    SobSelection: typeof import('./src/components/SobSelection.vue')['default']
    VoucherCreation: typeof import('./src/components/VoucherCreation.vue')['default']
    VoucherMain: typeof import('./src/components/VoucherMain.vue')['default']
  }
}

export { }
